### ISSUE TITLE
Sticky header does not work

### ISSUE THREAD

**Issue by zaherg** [extendify/extendable#154]
If I set a header group to sticky, it won't have the correct behaviour unless I moved it (in the inspector) outside the header template.

https://github.com/user-attachments/assets/c21afddd-6f09-4f3a-a1dd-bf2c0c35cf07

If I moved it outside the header template, it won't show at all

![image](https://github.com/user-attachments/assets/7941fac3-110a-4e61-8dd7-0aceb19756d8)

**Comment by amjadr360** [comment]
The issue seems to be that you’re setting the position: sticky inside the header container, which prevents it from working. To make it sticky, we either set sticky to the main header container, but the main header container doesn’t have position options. Therefore, to make the header sticky, we need to wrap it in another group block, set its position to sticky, assign a background, and make it full width. _There is no other native way to make it sticky_ 
 
Here is how we can make it sticky: 

https://github.com/user-attachments/assets/ebcf23d5-8083-4452-b6f6-1549503ded09


Now the question is how to make it sticky through Launch. 

One solution is to wrap the header in a group block with the properties we setted in the above video, for a single-page website only.


Here is the code 

```
<!-- wp:group {"metadata":{"name":"Sticky Header"},"style":{"position":{"type":"sticky","top":"0px"},"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"backgroundColor":"background","layout":{"type":"constrained"}} -->
<div
  class="wp-block-group has-background-background-color has-background"
  style="padding-top: 0; padding-right: 0; padding-bottom: 0; padding-left: 0"
>
  <!-- wp:template-part {"slug":"header","theme":"extendable","tagName":"header","align":"wide"} /-->
</div>
<!-- /wp:group -->

```

**Comment by amjadr360** [comment]
Or we create a custom CSS class for Sticky and add it to the header template part. For both these solutions we need to modify no-title.html template and changes will be saved in the user db such as we do for the header and footer templates.

**Comment by zaherg** [comment]
Yes, if we wrap it in a group as Amjad shown in the video we can set the position to that group.

I was going to suggest that we wrap the headers by default inside a group so we can control its position.
